// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWXW0O3uNexs-Cz9JArAqINa1zu7VwGiM',
    appId: '1:607534108011:android:d470776b8ef2dce0abd02e',
    messagingSenderId: '607534108011',
    projectId: 'concessiontrackerapp',
    storageBucket: 'concessiontrackerapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc4C8A8WjYtjEB7WrBSZxz5GuMFtBOgKU',
    appId: '1:607534108011:ios:8a76676fa5d18de0abd02e',
    messagingSenderId: '607534108011',
    projectId: 'concessiontrackerapp',
    storageBucket: 'concessiontrackerapp.firebasestorage.app',
    androidClientId: '607534108011-pq8o1cpdmqtsrajiscgmogqol9sj0f2k.apps.googleusercontent.com',
    iosClientId: '607534108011-1k3pe0cifhossddp5v7r1lomkdjn5ebj.apps.googleusercontent.com',
    iosBundleId: 'com.esoftsys.concessiontrackerapp',
  );
}
